### ISSUE TITLE
Placeholder with PlaceholderAPI ?

### ISSUE THREAD

**Issue by DianoxDragon** [caliog/Rolecraft#10]
Hi, I'd like to use a custom chat system, other than yours. The problem is that I can't, because I don't have PlaceholderAPI-compatible placeholders, or I don't know if they exist. The plugin is really good, too bad I'm missing a few placeholders.

**Comment by caliog** [comment]
Are you asking if Rolecraft supports Papi (not yet). You simply set the chat key in the config to "none" to disable Rolecraft's chat editing.

**Comment by DianoxDragon** [comment]
But even if I deactivate this chat, I can't really change it the way I want. I'm missing some placeholders.
