### ISSUE TITLE
Can't get items (weapons/armour) to work in-game when spaces in name

### ISSUE THREAD

**Issue by hades200082** [caliog/Rolecraft#3]

**Comment by caliog** [comment]
"to work"? If you want to access them you have to put the name in " ". E.g. /item  "Name with spaces".

**Comment by hades200082** [comment]
That's it exactly.  It might be better to define the name inside the yml instead of just using the filename ... that way the files can be named like "1-wolf.yml" for a lvl 1 mob but the name could just be "Wolf".

Or "5-BarbarianZombie.yml" could be "Barbarian Zombie".

It would also be nice to be able to name villagers, etc with spaces in their names.

**Comment by caliog** [comment]
This was done in Commit https://github.com/caliog/Rolecraft/commit/cdd74f86dd53ecb1b2ba13731e24573333778f1f
