### ISSUE TITLE
Various Issues in 1.12.2

### ISSUE THREAD

**Issue by Mrs-Feathers** [caliog/Rolecraft#9]
Hey, i'm using the newest Spigot build and i'm sure you know im using rolecraft v 3.2.10 since that's how i'm building spellcollection.jar.. but uh..

having spent most of my time just trying to make more spells [which has been successful so far, just trying to test it now.] i haven't tested much of anything else. so here are some things i've run into that seem out of place.. maybe you already are fixing it but maybe i'm helping in some way to report it to you..

1. when doing /item skillstar it says "I could not give you this item, does it really exist"
2. the config says `disable-natural-spawn:
  world: false` but its acting like its true and no hostile mobs spawn. only friendly mobs.
3. after using MIC.jar to create a few mobs, rolecraft doesn't seem to find the files, and /msz create fails for every mob saying "[name] is not a mob!"

and thus i can't level up to test any of the new spells. BUT they show up and all that :D so i'm really happy i didn't mess that up.

**Comment by caliog** [comment]
1. It only works with /item Skillstar, but I changed it to ignore case.
2. Cannot find anything wrong in the code here, have to check it later.
3. Did you find the files ? I think I didn't update the MIC in a while. Adding a line
    `name: <mob-name>`
to the .yml file should fix it. The name inside is the name displayed in game.

**Comment by Mrs-Feathers** [comment]
1. ok cool. ignoring the case is good, i dont normally capitalize things. even when i speak german :P 
2. ok. once rolecraft is disabled, mobs spawn normally again. so "something" about it doesn't like mob spawning... 
3. ah.. ok. thanks! since the MIC didn't have it, i didn't know it was supposed to be there tbh. [testing it now] aaand it works!! thanks!

Side Note: apparently issue #2 just fixed itself after i created a mob spawn zone. just a few skeletons and stuff spawned around me as if it was night, it was day light.. so they burnt up... then i went exploring.. seems to be normal now. no idea. switched it to night, monsters spawn as per normal. zero idea what happened there. maybe its just me? lol.

**Comment by caliog** [comment]
I just tested #2 at my server and it still works for me. Don't what happend there. Are friendly animals spawn at day time?

**Comment by Mrs-Feathers** [comment]
Yeah. Spawning works fine now. Day or night. Friendly and monsters

从飞蛾发来
